// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';

/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAck-WqhXzrDH85XYD1KD0Co-xF0LwrkUg',
    appId: '1:590181084714:web:09df369b66d9bd04431d53',
    messagingSenderId: '590181084714',
    projectId: 'digitalskill-96920',
    authDomain: 'digitalskill-96920.firebaseapp.com',
    storageBucket: 'digitalskill-96920.appspot.com',
    measurementId: 'G-JWFW1WSLLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClN-p0zT0yVXPk3zuiN70xalPbjM2IK1Q',
    appId: '1:590181084714:android:7f944618fc2221a8431d53',
    messagingSenderId: '590181084714',
    projectId: 'digitalskill-96920',
    storageBucket: 'digitalskill-96920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmu3o8Aeid9CU7sbguoAQE6zY1FiC3HdE',
    appId: '1:590181084714:ios:28bfb898cbacab81431d53',
    messagingSenderId: '590181084714',
    projectId: 'digitalskill-96920',
    storageBucket: 'digitalskill-96920.appspot.com',
    iosBundleId: 'com.example.digitalskill',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmu3o8Aeid9CU7sbguoAQE6zY1FiC3HdE',
    appId: '1:590181084714:ios:28bfb898cbacab81431d53',
    messagingSenderId: '590181084714',
    projectId: 'digitalskill-96920',
    storageBucket: 'digitalskill-96920.appspot.com',
    iosBundleId: 'com.example.digitalskill',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAck-WqhXzrDH85XYD1KD0Co-xF0LwrkUg',
    appId: '1:590181084714:web:a4ee7e42c86b3205431d53',
    messagingSenderId: '590181084714',
    projectId: 'digitalskill-96920',
    authDomain: 'digitalskill-96920.firebaseapp.com',
    storageBucket: 'digitalskill-96920.appspot.com',
    measurementId: 'G-5KEE00VV8C',
  );
}
